"""empty message

Revision ID: 67fa5e9f1082
Revises: 927b21f9c225
Create Date: 2021-06-02 14:10:22.690136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67fa5e9f1082'
down_revision = '927b21f9c225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_wall_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'wall_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('wall_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('posts_wall_id_fkey', 'posts', 'users', ['wall_id'], ['id'])
    # ### end Alembic commands ###
