"""empty message

Revision ID: 14c2c975f3db
Revises: 87e197886235
Create Date: 2021-06-02 15:11:28.372269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c2c975f3db'
down_revision = '87e197886235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_wall_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'wall_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('wall_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('posts_wall_id_fkey', 'posts', 'users', ['wall_id'], ['id'])
    # ### end Alembic commands ###
