"""empty message

Revision ID: 5c172087b1c4
Revises: ce9cf71ba15b
Create Date: 2021-06-10 16:31:32.038860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c172087b1c4'
down_revision = 'ce9cf71ba15b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('likes', 'comment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('likes', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('likes', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('likes', 'comment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
