"""empty message

Revision ID: 362431da311f
Revises: 14c2c975f3db
Create Date: 2021-06-02 18:36:40.803554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362431da311f'
down_revision = '14c2c975f3db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('comment_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'likes', 'comments', ['comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_column('likes', 'comment_id')
    # ### end Alembic commands ###
