"""empty message

Revision ID: e87d78a39b0e
Revises: 362431da311f
Create Date: 2021-06-03 21:22:52.336709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e87d78a39b0e'
down_revision = '362431da311f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_wall_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'wall_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('wall_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('posts_wall_id_fkey', 'posts', 'users', ['wall_id'], ['id'])
    # ### end Alembic commands ###
