"""empty message

Revision ID: 927b21f9c225
Revises: 69817e4c6871
Create Date: 2021-06-02 12:55:56.645397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927b21f9c225'
down_revision = '69817e4c6871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('user_a', sa.Integer(), nullable=False),
    sa.Column('user_b', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_a'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_b'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_a', 'user_b')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wall_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('photo_src', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wall_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('like_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('birthday', sa.Date(), nullable=False))
    op.add_column('users', sa.Column('cover_src', sa.String(length=500), nullable=False))
    op.add_column('users', sa.Column('location', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('profile_src', sa.String(length=500), nullable=False))
    op.add_column('users', sa.Column('school', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('work', sa.String(length=50), nullable=True))
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.VARCHAR(length=360), autoincrement=False, nullable=True))
    op.drop_column('users', 'work')
    op.drop_column('users', 'school')
    op.drop_column('users', 'profile_src')
    op.drop_column('users', 'location')
    op.drop_column('users', 'cover_src')
    op.drop_column('users', 'birthday')
    op.drop_table('likes')
    op.drop_table('comments')
    op.drop_table('posts')
    op.drop_table('friends')
    # ### end Alembic commands ###
