"""empty message

Revision ID: 87e197886235
Revises: 67fa5e9f1082
Create Date: 2021-06-02 14:49:01.208776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e197886235'
down_revision = '67fa5e9f1082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('wall_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'posts', 'users', ['wall_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'wall_id')
    # ### end Alembic commands ###
